import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

/**
 * Exports session doubt feed to PDF document
 */
export function exportSessionToPDF(sessionData) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const { code, createdAt, endedAt, participantCount, totalDoubts, doubts } = sessionData;

  // Header Banner
  doc.setFillColor(15, 23, 42); // Dark background
  doc.rect(0, 0, 210, 35, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(99, 102, 241); // Indigo primary
  doc.text('Doubt Undo?', 14, 18);

  doc.setFontSize(11);
  doc.setTextColor(203, 213, 225);
  doc.text(`Live Class Session Archive  •  Code: ${code}`, 14, 26);

  // Metadata Card
  doc.setFillColor(248, 250, 252);
  doc.roundedRect(14, 40, 182, 28, 3, 3, 'F');
  doc.setDrawColor(226, 232, 240);
  doc.roundedRect(14, 40, 182, 28, 3, 3, 'D');

  doc.setFontSize(9);
  doc.setTextColor(100, 116, 139);
  doc.text('SESSION METADATA', 18, 47);

  doc.setFontSize(10);
  doc.setTextColor(15, 23, 42);
  doc.setFont('helvetica', 'normal');
  const startDateStr = new Date(createdAt).toLocaleString();
  const endDateStr = endedAt ? new Date(endedAt).toLocaleString() : 'Active / Continuous';
  
  doc.text(`Created: ${startDateStr}`, 18, 54);
  doc.text(`Ended: ${endDateStr}`, 18, 61);
  doc.text(`Participants: ${participantCount || 1}`, 110, 54);
  doc.text(`Total Doubts: ${totalDoubts || doubts.length}`, 110, 61);

  // Sort doubts: Upvotes (descending), then chronologically
  const sortedDoubts = [...doubts].sort((a, b) => {
    if (b.upvotes !== a.upvotes) return b.upvotes - a.upvotes;
    return b.createdAt - a.createdAt;
  });

  // Prepare table rows
  const tableRows = sortedDoubts.map((doubt, index) => {
    const statusText = (doubt.status || 'pending').toUpperCase();
    const mediaBadge = doubt.mediaType ? ` [Media: ${doubt.mediaType}]` : '';
    const content = `${doubt.text || '(No text content)'}${mediaBadge}${doubt.teacherReply ? `\n\n↳ Teacher Answer: "${doubt.teacherReply}"` : ''}`;

    return [
      index + 1,
      doubt.handle || 'Anonymous',
      doubt.upvotes || 0,
      statusText,
      content
    ];
  });

  // Render Table
  autoTable(doc, {
    startY: 75,
    head: [['#', 'Author', 'Upvotes', 'Status', 'Doubt Content & Teacher Answer']],
    body: tableRows,
    theme: 'grid',
    headStyles: {
      fillColor: [99, 102, 241],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 10
    },
    columnStyles: {
      0: { cellWidth: 10, halign: 'center' },
      1: { cellWidth: 28, fontStyle: 'bold' },
      2: { cellWidth: 20, halign: 'center', fontStyle: 'bold' },
      3: { cellWidth: 26, halign: 'center' },
      4: { cellWidth: 'auto' }
    },
    styles: {
      fontSize: 9,
      cellPadding: 4,
      overflow: 'linebreak'
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252]
    }
  });

  // Footer on every page
  const totalPages = doc.internal.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(148, 163, 184);
    doc.text(`Generated by Doubt Undo?  •  Page ${i} of ${totalPages}`, 105, 287, { align: 'center' });
  }

  // Trigger browser download
  doc.save(`DoubtUndo_Session_${code}.pdf`);
}
